sudo: false
branches:
  only:
    - master
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
      env: TASKS="pytest(acquisition), clang-format"
    - os: linux
      dist: trusty
      python: 3.4
      env: TASKS="pytest(acquisition), flake8"
    - language: generic
      os: osx
      osx_image: xcode8.3
      env: TASKS="ctest"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.8
    packages:
    - clang-format-3.8
install:
  - cd $HOME
  - travis_wait 20 $TRAVIS_BUILD_DIR/scripts/travis/install.sh
script:
  - cd $HOME
  - env
  - $TRAVIS_BUILD_DIR/scripts/travis/build.sh
