os: Visual Studio 2015
platform: x64
cache:
  - C:\projects\paraview.zip
  - C:\projects\paraview.zip.sha512
  - C:\projects\itk-4.9.0-windows-64bit.zip
  - C:\projects\itk-4.9.0-windows-64bit.zip.sha512
  - C:\projects\tbb.zip
  - C:\projects\tbb.zip.sha512
  - C:\projects\python-3.6.0.zip
  - C:\projects\python-3.6.0.zip.sha512
  - C:\projects\googletest-install.zip
  - C:\projects\googletest-install.zip.sha512
  - C:\projects\numpy.zip
  - C:\projects\numpy.zip.sha512
install:
  # Take care of submodules
  - git submodule sync
  - git submodule update --init
  - cd ..
  # Restore our cached deps
  - C:\Python36\python.exe -m pip install -U pip
  - C:\Python36\python.exe -m pip install requests
  - C:\Python36\python.exe %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\cache_restore.py

build_script:
  # Setup PATH
  - set PATH=C:\projects\tomviz-build\lib\site-packages\tomviz;%PATH%
  - set PATH=C:\projects\python\bin;%PATH%
  - set PATH=c:\projects\python;%PATH%
  - set PATH=C:\projects\tbb\bin\intel64\vc14;%PATH%
  - set PATH=C:\projects\paraview-build\lib;%PATH%
  - set PATH=C:\projects\paraview-build\bin;%PATH%
  - set PATH=C:\Qt\5.10.0\msvc2015_64\bin;%PATH%
  # Setup PYTHONPATH
  - set PYTHONPATH=C:/projects/python/bin/Lib
  - set PYTHONPATH=C:/projects/python/bin/Lib/site-packages;%PYTHONPATH%
  - set PYTHONPATH=C:/projects/paraview-build/bin;%PYTHONPATH%
  - set PYTHONPATH=C:/projects/tomviz-build/lib/site-packages;%PYTHONPATH%
  - set PYTHONPATH=C:/projects/paraview-build/lib/site-packages;%PYTHONPATH%
  - set PYTHONPATH=C:/projects/paraview-build/lib;%PYTHONPATH%
  # Set PYTHONHOME
  - set PYTHONHOME=C:/projects/python/bin
  # Install acquisition test requirements
  - set TOMVIZ_TEST_PYTHON_EXECUTABLE=C:\projects\python\bin\python.exe
  - C:\projects\python\bin\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\acquisition\requirements-dev.txt
  # Now call ctest
  - ctest -VV -S %APPVEYOR_BUILD_FOLDER%\cmake\AppVeyorContinuous.cmake
